name: Build OpenELIS-Global-2 Installer
on:
  workflow_dispatch:
    
jobs:
  check-out-and-build-installer:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout OpenELIS-Global2
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          submodules: recursive

      - name: Build installer
        run: ./build.sh -ib develop

      - name: check installer
        run: ls OEInstaller/linux  
 
